USE sakila;
-- List the number of films per category
SELECT 
    c.name AS category_name, 
    COUNT(fc.film_id) AS total_films
FROM category AS c # here AS is optional you can skip it but better to write for understanding 
JOIN film_category AS fc ON c.category_id = fc.category_id
GROUP BY c.category_id, c.name
ORDER BY total_films DESC;

-- Retrieve the store ID, city, and country for each store
SELECT 
    s.store_id, 
    ci.city, 
    co.country
FROM store s
JOIN address a ON s.address_id = a.address_id
JOIN city ci ON a.city_id = ci.city_id
JOIN country co ON ci.country_id = co.country_id;

--  Calculate the total revenue generated by each store in dollars
SELECT 
    s.store_id, 
    SUM(p.amount) AS total_revenue_dollars
FROM store s
JOIN staff st ON s.store_id = st.store_id
JOIN payment p ON st.staff_id = p.staff_id
GROUP BY s.store_id;

-- Determine the average running time of films for each category

SELECT 
    c.name AS category_name, 
    ROUND(AVG(f.length), 2) AS average_running_time
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name
ORDER BY average_running_time DESC;

-- Display the top 10 most frequently rented movies in descending order
SELECT 
    f.title, 
    COUNT(r.rental_id) AS rental_frequency
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.film_id, f.title
ORDER BY rental_frequency DESC
LIMIT 10;

-- Determine if "Academy Dinosaur" can be rented from Store '1' and shows how many copies are in stock
SELECT 
    f.title, 
    i.store_id, 
    COUNT(i.inventory_id) AS copies_in_stock
FROM film f
JOIN inventory i ON f.film_id = i.film_id
WHERE f.title = 'ACADEMY DINOSAUR' 
  AND i.store_id = 1
GROUP BY f.title, i.store_id;










